# Theme metadata
name = "CMU"

# Is theme light or dark?
light = true

# Primary
primary = "#A6192E"

# Menu
menu_primary = "#A6192E"
menu_text = "#fff"
menu_text_active = "#F2A900"
menu_title = "#fff"

# Home sections
home_section_odd = "#fff"
home_section_even = "#fff"
